import type { Metadata } from "next";
import localFont from "next/font/local";
import "@/styles/globals.css";

const notoSansJP = localFont({
  src: "../../public/fonts/NotoSansJP-VariableFont_wght.ttf",
  variable: "--font-noto-sans-jp",
  display: "swap",
});

const teko = localFont({
  src: "../../public/fonts/Teko-VariableFont_wght.ttf",
  variable: "--font-teko",
  display: "swap",
});

const font404 = localFont({
  src: "../../public/fonts/404.woff2",
  variable: "--font-404",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${notoSansJP.variable} ${teko.variable} ${font404.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
