import type { Metadata } from "next";
import localFont from "next/font/local";
import { Geist_Mono } from "next/font/google";
import "@/styles/globals.css";

const notoSansJP = localFont({
  src: "../../public/fonts/NotoSansJP-VariableFont_wght.ttf",
  variable: "--font-noto-sans-jp",
  display: "swap",
});

const teko = localFont({
  src: "../../public/fonts/Teko-VariableFont_wght.ttf",
  variable: "--font-teko",
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${notoSansJP.variable} ${teko.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
