import type { Metadata } from "next";
import localFont from "next/font/local";
import { Geist_Mono, Syne } from "next/font/google";
import "@/styles/globals.css";

const notoSansJP = localFont({
  src: "../../public/fonts/NotoSansJP-VariableFont_wght.ttf",
  variable: "--font-noto-sans-jp",
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const syne = Syne({
  variable: "--font-syne",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${notoSansJP.variable} ${geistMono.variable} ${syne.variable}`}>
        {children}
      </body>
    </html>
  );
}
